Changed ini parser to my own code

diff --git a/usr/sbin/manage-ca b/usr/sbin/manage-ca
--- a/usr/sbin/manage-ca
+++ b/usr/sbin/manage-ca
@@ -198,47 +198,60 @@ EOFILE
 
 modify_ssl_config() {
 	echo Changing ssl config
-	
+	if ! [ -e "$1" ]; then
+		echo "ERROR: SSL Config file does not exist"
+		exit 1
+	fi
 }
-
-### Beginning included code from https://github.com/chilladx/config-parser
-# TODO[bplainia]: ignore code. add prefix instead of calling sections.
-config_parser () {
-	local iniFile="$1";
-	local tmpFile=$( mktemp /tmp/`basename $iniFile`.XXXXXX );
-	local intLines;
-	local binSED=$( which sed );
-
-	# copy the ini file to the temporary location
-	cp $iniFile $tmpFile;
-
-	# remove tabs or spaces around the =
-	$binSED -i -e 's/[ \t]*=[ \t]*/=/g' $tmpFile;
-
-	# transform section labels into function declaration
-	$binSED -i -e 's/\[\([A-Za-z0-9_]*\)\]/config.section.\1() \{/g' $tmpFile;
-	$binSED -i -e 's/config\.section\./\}\'$'\nconfig\.section\./g' $tmpFile;
-
-	# remove first line
-	$binSED -i -e '1d' $tmpFile;
-
-	# add the last brace
-	echo -e "\n}" >> $tmpFile;
-
-	# now load the file
-	source $tmpFile;
-
-	# clean up
-	rm -f $tmpFile;
-}
-### End of INI reader code
 
 # before we read the switches, we need to read the config file, if it exists.
 read_my_config() {
+	local iniFile="$1";
+	local section="NONE"
+	local sectRegex="^[ \t]*\[[ \t]*([A-Za-z0-1]+)[ \t]*\][ \t]*"
+	local varRegex='^[ \t]*([A-Za-z0-9_]*)=("[^\n"]*"|[A-Za-z0-9_]*|[\d]+\.?[\d]*)(?:[ \t]*#.*)?$'
+	local comRegex="^[ \t]*#.*$"
+	local lineNo=0
+	local items=0
+	
+	if ! [ -e $iniFile ]; then
+		echo "ERROR: Config file not found! I need it to work."
+		exit 502
+	fi
+	
 	echo Reading Configuration File
-	config_parser $configfile
-	# select a section by calling config.section.<section>
-	# config.section.global
+	# parse the file
+	while IFS='' read -r str
+	do
+		((lineNo=lineNo + 1))
+		if [[ $str =~ $sectDelimiter ]]; then
+			$section=${BASH_REMATCH[1]}
+		elif [[ $str =~ $varRegex ]]; then
+			case "${BASH_REMATCH[1]}" in
+				directory) 
+					directory=${BASH_REMATCH[2]} 
+					((items=items + 1))
+					;;
+				version)
+					if [[ ${BASH_REMATCH[2]} != $version ]]; then
+						echo "ERROR: Config Version does not match"
+						exit 503
+					fi
+					((items=items + 1)) ;;
+				*) 
+					echo "WARNING: Unknown variable on line $lineNo."
+			esac
+		elif [[ $str =~ $comRegex ]]; then
+			continue
+		else
+			echo "ERROR: Error in config file on line $lineNo."
+			exit 504
+		fi
+	done < $iniFile
+	if [ $items -lt 2 ]; then
+		echo "ERROR: Not enough required elements"
+		exit 505
+	fi
 }
 
 write_my_config() {
@@ -326,13 +339,16 @@ done
 # end of the switches. now for commands
 case "$1" in
 	list|l)
-		echo "Cannot list certificates or CA's" ;;
+		echo "Cannot list certificates or CA's" 
+		;;
 	new|n)
 		shift
 		# TODO: New ca, user, or server
-		echo "Cannot make new certificates yet" ;;
+		echo "Cannot make new certificates yet" 
+		;;
 	config|c)
-		echo "Cannot configure. I don't know how" ;;
+		echo "Cannot configure. I don't know how" 
+		;;
 	help|h)
 		shift
 		help_funct $1 ;;
